### PR TITLE
Add production and crafting queue tabs.

### PR DESCRIPTION
**Pull request by randomdud3**
I know tabs aren't the best place for this, and there is no tournament mode version or whatever that doesn't show the other team stats, but atm i just wanna know if it's something useful for people spectating or whatnot

prodtab
craftab

### CODE REVIEW

**Comment by M3wM3w** [comment]
this needs to be more tidy, don't like this tab mess

**Comment by randomdud3** [comment]
You mean you don't like them being tabs, or the tabs content need to change?

**Comment by M3wM3w** [comment]
maybe it would fit better if the minimal width was removed of the tab captions

**Comment by Gerkiz** [comment]
Hello,
Maybe make a tab and store `Prod` and `Crafting` under there?

**Comment by randomdud3** [comment]
I dunno what's the best path here, but honestly I wanna get this out specially with the amount of casting of pickup and tournament lately. So if you see any way to get this sorted out @M3wM3w, just let me know and ill work towards it

**Comment by guppyfaced** [comment]
Has this feature been shelved or does it need resolving before merging? @M3wM3w

**Pull request closed without merging**
