### PR TITLE
Mutagen log filters : bug fix and 3 filters added (force, science, evo jump)

### PR DESCRIPTION
**Pull request by Masamune0**
Relate to https://github.com/M3wM3w/ComfyFactorio/issues/125 :

->Fix custom names of team (if someone switchs name in a match, then the oldest line will have the previous name, new lines will have the new line)
->Add total summary for throw
->Add force filter(North/south/all)
->Add science filter (very high tier/high tier/med tier+, then all other sciences one by one only)
->Add evo jump filter (don't show +0 evo jump, show only 1+ evo jump and so on...)
->Add passive feed information

### CODE REVIEW

**Comment by M3wM3w** [comment]
Is this desync safe?
`
local dropdown_users_choice_force = {}
local dropdown_users_choice_science = {}
local dropdown_users_choice_evo_filter = {}
`

Also there could be more loops for less code repeatings.

**Comment by Masamune0** [comment]
Okay I'm going to fix the part where code is repeating.

For your desync question, I have no idea, what do you advise to do instead?

**Comment by Masamune0** [comment]
@M3wM3w
Okay I'm going to fix the part where code is repeating.

For your desync question, I have no idea, what do you advise to do instead?

**Comment by Masamune0** [comment]
Added more loops to avoid code repeating

**Comment by Masamune0** [comment]
Mmh, made the dropdown global, should be fine now ? or not?

**Comment by Masamune0** [comment]
Tried in solo with 2 players, didn't have any desynch issue (other player was switching filters in mutagen log, open/close it, did that for two players, nothing happened). I guess it is because it is global + all in functions, so no desynch issue?

**Comment by Masamune0** [comment]
Hold on, with heavy mode : 
image
No clue how to fix that for the time being.

**Comment by Masamune0** [comment]
Okay fixed the error by using the small part of code of main for refreshing gui. Better frame handling now

**Pull request merged**
